# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 65871c7c1cbe9756dd7178b612f394cfa44a81f1e9bddd361232262cac0970c7908cd68aa083ecf089f4b414e5d97d93eaa738a5a178fdad36c32a0d8188297e

test:
  secret_key_base: 261bdb29fc3ff3fdfe9b36c2cba222db53ad58780899227e38636f53b84c4f414c0582da1d803457a5e4bab816c82a3c49608e608f8941bc54b08724199f0c00

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  # o ideal aqui seria isso:  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # talvez até mesmo colocando para ser regerado sempre que fizer o deploy, mas de forma simples, deveria estar em um
  # arquivo na máquina ou simplesmente como variável de ambiente no host
  secret_key_base: 48f35e061d571f0b38eb09e18a35f46937e4c65826df56e05657d7d0c1ceb35c9de9c1bfedf02edbf62b7122dfba0452ada212a91f89d2c5cc289e981f0e5862
